services:
  aemet-warnings:
    container_name: aemet_warnings
    build:
      context: .
    restart: ${RESTART_POLICY}
    command: sh -c "/wait && ./docker-entrypoint.sh && gunicorn --bind 0.0.0.0:8000 dustwarning:app"
    volumes:
      - ${STATE_VOLUME}:/data/state
      - ${BOUNDARY_DATA_VOLUME}:/data/boundary_data
    environment:
      - DEBUG=False
      - LOG=${LOG}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_TIMEOUT=60
      - STATE_DIR=/data/state
      - BOUNDARY_DATA_DIR=/data/boundary_data
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
      - FLASK_APP=dustwarning/__init__.py
    ports:
      - 8000
networks:
  default:
    name: ${AHW_DOCKER_NETWORK}
    external: true