services:
  aemet-warnings:
    container_name: aemet_warnings
    build:
      context: .
      args:
        - DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX=${DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX:-}
    restart: ${RESTART_POLICY}
    command: sh -c "/wait && ./docker-entrypoint.sh && gunicorn --bind 0.0.0.0:8000 dustwarning:app"
    volumes:
      - ${STATE_VOLUME}:/data/state
    environment:
      - DEBUG=False
      - WAIT_HOSTS=aemet_db:5432
      - WAIT_TIMEOUT=60
      - STATE_DIR=/data/state
      - SQLALCHEMY_DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@aemet_db:5432/${DB_NAME}
      - FLASK_APP=dustwarning/__init__.py
      - COUNTRY_ISO_CODES=${COUNTRY_ISO_CODES}
    ports:
      - 8000
  aemet-db:
    image: ${DB_IMAGE:-postgis/postgis:15-master}
    container_name: aemet_db
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432
  aemet-pg-tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: aemet_pg_tileserv
    restart: ${RESTART_POLICY}
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@aemet_db:5432/${DB_NAME}
    ports:
      - 7800

  networks:
    default:
      external: true
      name: ${DOCKER_NETWORK_NAME}