boundary_config = {
    "BFA": {
        "country": "Burkina Faso",
        "iso": "BFA",
        "fields": {
            "ENGTYPE_1": "Region",
            "HASC_1": "BF.BO",
            "ID_0": 38,
            "ID_1": 1,
            "ISO": "BFA",
            "NAME_0": "Burkina Faso",
            "NAME_1": "Boucle du Mouhoun",
            "NL_NAME_1": "",
            "TYPE_1": "Région",
        },
        "id_field": "HASC_1",
        "name_field": "NAME_1",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/burkinafaso/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    },
    "SEN": {
        "country": "Senegal",
        "iso": "SEN",
        "fields": {
            "ADM0_FR": "Senegal",
            "ADM0_PCODE": "SN",
            "ADM1ALT1FR": "",
            "ADM1ALT2FR": "",
            "ADM1_FR": "Dakar",
            "ADM1_PCODE": "SN01",
            "ADM1_REF": "",
        },
        "id_field": "ADM1_PCODE",
        "name_field": "ADM1_FR",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/senegal/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    },
    "TCD": {
        "country": "Chad",
        "iso": "TCD",
        "fields": {
            "admin0Name": "Tchad",
            "admin0Pcod": "TD",
            "admin1Al_1": "",
            "admin1AltN": "",
            "admin1Na_1": "BATHA",
            "admin1Name": "Batha",
            "admin1Pcod": "TD01",
            "admin1RefN": "Batha",
        },
        "id_field": "admin1Pcod",
        "name_field": "admin1Name",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/chad/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    },
    "MLI": {
        "country": "Mali",
        "iso": "MLI",
        "fields": {
            "ADM0_FR": "Mali (le)",
            "ADM0_PCODE": "ML",
            "ADM1ALT1FR": "",
            "ADM1ALT2FR": "",
            "ADM1_FR": "Kayes",
            "ADM1_PCODE": "ML01",
            "ADM1_REF": "",
        },
        "id_field": "ADM1_PCODE",
        "name_field": "ADM1_FR",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/mali/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    },
    "NER": {
        "country": "Niger",
        "iso": "NER",
        "fields": {
            "ISO2": "NE",
            "ISO3": "NER",
            "NOMREG": "AGADEZ",
            "OBJECTID": 1,
            "adm_01": "Agadez",
            "rowcacode1": "NER001",
        },
        "id_field": "rowcacode1",
        "name_field": "adm_01",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/niger/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    },
    "CPV": {
        "country": "Cape Verde",
        "iso": "CPV",
        "fields": {
            "Ilha_1": "BOAVISTA",
            "OBJECTID": 1.0,
        },
        "id_field": "Ilha_1",
        "name_field": "Ilha_1",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/cabo_verde/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    },
    "MRT": {
        "country": "Mauritania",
        "iso": "MRT",
        "fields": {
            "ADM0_EN": "Mauritania",
            "ADM0_PCODE": "MR",
            "ADM1ALT1EN": "",
            "ADM1ALT2EN": "",
            "ADM1_EN": "Adrar",
            "ADM1_PCODE": "MR01",
            "ADM1_REF": "",
        },
        "id_field": "ADM1_PCODE",
        "name_field": "ADM1_EN",
        "geojson_url_template": "https://dust.aemet.es/daily_dashboard/assets/geojsons/was/mauritania/geojson/{date_str}/{date_str}_SCONC_DUST_{day_val}.geojson",
    }
}
