"""empty message

Revision ID: 11b15148079b
Revises: 1bb385bb6278
Create Date: 2025-04-22 13:54:48.201742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b15148079b'
down_revision = '1bb385bb6278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
