"""Add warnings

Revision ID: 337963de1325
Revises: d7f9367788dd
Create Date: 2023-11-16 14:42:48.788352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337963de1325'
down_revision = 'd7f9367788dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aemet_dust_warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(length=256), nullable=False),
    sa.Column('init_date', sa.DateTime(), nullable=False),
    sa.Column('day_one_val', sa.Integer(), nullable=False),
    sa.Column('day_two_val', sa.Integer(), nullable=False),
    sa.Column('day_three_val', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['aemet_country_boundary.gid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gid', 'init_date', name='unique_dust_warming_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aemet_dust_warning')
    # ### end Alembic commands ###
