"""Initial migration.

Revision ID: d7f9367788dd
Revises: 
Create Date: 2023-11-16 11:55:47.136140

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'd7f9367788dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('aemet_country_boundary',
    sa.Column('gid', sa.String(length=256), nullable=False),
    sa.Column('country_iso', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('gid')
    )
    with op.batch_alter_table('aemet_country_boundary', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_aemet_country_boundary_geom', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aemet_country_boundary', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_aemet_country_boundary_geom', postgresql_using='gist', column_name='geom')

    op.drop_geospatial_table('aemet_country_boundary')
    # ### end Alembic commands ###
